### ISSUE TITLE
EnderIO and Exchangers Issue

### ISSUE THREAD

**Issue by Akiishii** [JackyyTV/Exchangers#45]
Minecraft Version 1.12.2
Forge Version: 14.23.2.2617

java.lang.RuntimeException: Invalid shaped ore recipe: IBI, ICI, IBI, I, ingotConductiveIron, B, null, C, jackyy.exchangers.item.enderio.ItemEIOExchangerCoreT1@116f2e65, 
	at net.minecraftforge.common.crafting.CraftingHelper.parseShaped(CraftingHelper.java:344)
	at net.minecraftforge.fml.common.registry.GameRegistry.addShapedRecipe(GameRegistry.java:202)
	at jackyy.exchangers.Recipes.init(Recipes.java:190)
	at jackyy.exchangers.proxy.CommonProxy.onRecipeRegistry(CommonProxy.java:41)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_581_CommonProxy_onRecipeRegistry_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:143)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:746)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:622)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:718)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:337)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Thread.java:748)

**Comment by JackyyTV** [comment]
I am aware of the issue, Exchangers currently doesn't work with Ender IO on 1.11+, but it's fixed in the dev branch, new version will be out in a few days.

**Comment by JackyyTV** [comment]
Fixed in [2.7](https://minecraft.curseforge.com/projects/exchangers/files/2532994).
