### ISSUE TITLE
Duplication glitch when using Chisels & Bits -- Direwolf20 1.12

### ISSUE THREAD

**Issue by Raidobw2** [JackyyTV/Exchangers#50]
Hi Jacky, 

Currently playing on a server with [FTB Presents Direwolf20 1.12] and i found a dupe glitch using any exchanger with a "Chiseled Bit Bag" from Chisels & Bits. Basically any normal block, for example stone, can be shift-clicked with an exchanger as usual, then if you have the Chiseled Bit Bag in your inventory and you right-click a wood log with the exchanger but without having any stone in your inventory it throws an error in the server console but converts the wood block to a stone block, so you basically just duped a stone block. Meaning it can dupe any late game material, example you can convert your entire house with diamond blocks. Of course the error is in red so this is probably not intended :^) (but there isn't any in-game chat log from this bug).

This is the error (don't mind the time, server clock bugged out i think, it's rented):
```
[23:20:44] [FATAL] Error executing task
[19:20:44] java.util.concurrent.ExecutionException: java.lang.ClassCastException: mod.chiselsandbits.bitbag.BagCapabilityProvider cannot be cast to net.minecraftforge.items.wrapper.InvWrapper
[19:20:44] at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_131]
[19:20:44] at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_131]
[19:20:44] at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
[19:20:44] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
[19:20:44] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
[19:20:44] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
[19:20:44] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
[19:20:44] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

```
Followed by the cause on the next console line:
```
[19:20:44] Caused by: java.lang.ClassCastException: mod.chiselsandbits.bitbag.BagCapabilityProvider cannot be cast to net.minecraftforge.items.wrapper.InvWrapper
[19:20:44] at jackyy.exchangers.handler.ExchangerHandler.findItemHolder(ExchangerHandler.java:414) ~[ExchangerHandler.class:?]
[19:20:44] at jackyy.exchangers.handler.ExchangerHandler.consumeItemInInventory(ExchangerHandler.java:391) ~[ExchangerHandler.class:?]
[19:20:44] at jackyy.exchangers.handler.ExchangerHandler.placeBlock(ExchangerHandler.java:223) ~[ExchangerHandler.class:?]
[19:20:44] at jackyy.exchangers.handler.ExchangerHandler.func_180614_a(ExchangerHandler.java:163) ~[ExchangerHandler.class:?]
[19:20:44] at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:860) ~[ForgeHooks.class:?]
[19:20:44] at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) ~[aip.class:?]
[19:20:44] at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:489) ~[or.class:?]
[19:20:44] at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) ~[pa.class:?]
[19:20:44] at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
[19:20:44] at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
[19:20:44] at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
[19:20:44] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_131]
[19:20:44] at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_131]
[19:20:44] at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
[19:20:44] ... 5 more
```
I hope this can be helpful! I don't go on Github often but i'll recheck every few days if you need me to reproduce the bug and link a picture.

Antoine

**Comment by JackyyTV** [comment]
That has been fixed ages ago, I think you're on an older version of DW20 because [1.10.0](https://www.feed-the-beast.com/projects/ftb-presents-direwolf20-1-12/files/2541242) has the patch for that already.
