### ISSUE TITLE
1.12.2 Crashing when opening Exchanger config

### ISSUE THREAD

**Issue by yulescholtissek** [JackyyTV/Exchangers#69]
Hey, I just installed Exchangers and whenever I try to open the GUI to configure it, my game crashes. 

Here is the crash log:
Time: 8/20/23 3:09 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at jackyy.exchangers.client.gui.ExchangersGuiScreen.func_73866_w_(ExchangersGuiScreen.java:68)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1018)
	at jackyy.exchangers.handler.ClientEventsHandler.onKeyInput(ClientEventsHandler.java:176)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2473_ClientEventsHandler_onKeyInput_KeyInputEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireKeyInput(FMLCommonHandler.java:565)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2017)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Thanks in advance for all the help.

**Comment by JackyyTV** [comment]
Do you have the full crash report? This is not supposed to happen and I need to have a look into what's going on.

**Comment by JackyyTV** [comment]
I have a new test version for you to try out, if this fixes your issue, then I think I know what's wrong.
[Download link](https://jackyy.hk/stuff/minecraft/jars/Exchangers-1.12.2-2.10.3-TEST.jar)

**Comment by yulescholtissek** [comment]
The new version you sent is working perfectly fine. Thanks for the fast help! :)

**Comment by JackyyTV** [comment]
Alright cool, in that case, I'll leave this issue open for now until the new version gets released, which will be within a few days.

**Comment by JackyyTV** [comment]
New version is now out on CurseForge:
[Download link](https://www.curseforge.com/minecraft/mc-mods/exchangers/files/4732479)
