### ISSUE TITLE
Hardend Exchanger Crashes after going past 25x25 mode.

### ISSUE THREAD

**Issue by darkphan** [JackyyTV/Exchangers#9]
Version: 1.1
Forge: 12.18.3.2316

When changing modes on a hardend exchanger past 25x25 client crashed with:

Time: 7/10/17 9:43 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 13
	at me.jacky1356400.exchangers.handler.GUIHandler.onGameOverlayRender(GUIHandler.java:88)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1232_GUIHandler_onGameOverlayRender_RenderGameOverlayEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:888)
	at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:586)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:167)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1072)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by JackyyTV** [comment]
I know what's causing the crash. Hardened exchanger was meant to do only 7x7 area, Will push a fix soon.

**Comment by darkphan** [comment]
Not sure if this was fixed yet or not, but the current version that came out after your post still has the issue. Thanks again!

**Comment by JackyyTV** [comment]
I did release 1.2 before this issue opened, but it's not fixed yet by the looks of it, I am just trying to fix everything at once before releasing another update.

**Comment by JackyyTV** [comment]
Fixed in [1.10.2-1.3](https://github.com/Jacky1356400/Exchangers/releases/tag/1.10.2-1.3).
